# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azrl < Formula
  desc "Azure Remote Login — manage multiple Azure accounts via isolated, directory-scoped profiles"
  homepage "https://github.com/slamb2k/azrl"
  version "0.21.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slamb2k/azrl/releases/download/v0.21.0/azrl_0.21.0_darwin_amd64.tar.gz"
      sha256 "dad09ffca360af0b4c606e1351ec4426bd9047459e4ba545048aaa08de6d66e1"

      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slamb2k/azrl/releases/download/v0.21.0/azrl_0.21.0_darwin_arm64.tar.gz"
      sha256 "4ef2d4141dc8086687212abd460b7e0d48b55584a773bdc6620d9f391712f52f"

      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slamb2k/azrl/releases/download/v0.21.0/azrl_0.21.0_linux_amd64.tar.gz"
      sha256 "02ff54e539a3ecca26edd75d5c761d643b8adbef11a304c58dc8591661cafed1"
      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slamb2k/azrl/releases/download/v0.21.0/azrl_0.21.0_linux_arm64.tar.gz"
      sha256 "8d045b8afdb091489c29823a8ac9b2542f8407045c994a1bcf12c65586e52ac7"
      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
  end

  test do
    system "#{bin}/azrl", "--version"
    system "#{bin}/ghrl", "--version"
  end
end
