# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azrl < Formula
  desc "Azure Remote Login — manage multiple Azure accounts via isolated, directory-scoped profiles"
  homepage "https://github.com/slamb2k/azrl"
  version "0.53.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slamb2k/azrl/releases/download/v0.53.0/azrl_0.53.0_darwin_amd64.tar.gz"
      sha256 "0238efc4e1c45a495c915e0ba4e343fdd9680fd11d36f7bf746f9dbf298fc823"

      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slamb2k/azrl/releases/download/v0.53.0/azrl_0.53.0_darwin_arm64.tar.gz"
      sha256 "38611d905d38b5b418a79e95a5c3de03ac3547f7bb6edebe42636a373979e7f5"

      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slamb2k/azrl/releases/download/v0.53.0/azrl_0.53.0_linux_amd64.tar.gz"
      sha256 "5827970c2b066dc158fc92a7a1c2cdb5e188384c833a7ab2b9a7b5a6d112e6f7"
      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slamb2k/azrl/releases/download/v0.53.0/azrl_0.53.0_linux_arm64.tar.gz"
      sha256 "02713b17e5de20f53a8e0dfbc6730cc058f3f25de95ad983fff2045698224156"
      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
  end

  test do
    system "#{bin}/azrl", "--version"
    system "#{bin}/ghrl", "--version"
  end
end
