# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azrl < Formula
  desc "Azure Remote Login — manage multiple Azure accounts via isolated, directory-scoped profiles"
  homepage "https://github.com/slamb2k/azrl"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slamb2k/azrl/releases/download/v0.15.0/azrl_0.15.0_darwin_amd64.tar.gz"
      sha256 "26b80dc44bd8d9b560e2f990103a6396912149dce605d4a23252db4958de826d"

      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slamb2k/azrl/releases/download/v0.15.0/azrl_0.15.0_darwin_arm64.tar.gz"
      sha256 "2c27ada7b87a53a43f1be8be637d441b2cbdf5e1b779aecd63627c1b3d12af4b"

      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slamb2k/azrl/releases/download/v0.15.0/azrl_0.15.0_linux_amd64.tar.gz"
      sha256 "f42d36e82be027fd4fd0b711cf419653b8e24d3bc8e0220a4dbb636c8d2ac83a"
      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slamb2k/azrl/releases/download/v0.15.0/azrl_0.15.0_linux_arm64.tar.gz"
      sha256 "89b91ea23119ea92a514604f597093e4022783e5ac120b2eff0c183e93110f51"
      define_method(:install) do
        bin.install "azrl"
        bin.install "ghrl"
      end
    end
  end

  test do
    system "#{bin}/azrl", "--version"
    system "#{bin}/ghrl", "--version"
  end
end
